spring:
  datasource:
    username: sqladmin@sunshineutedb
    password: Thuyhang2001
    url: jdbc:sqlserver://sunshineutedb.database.windows.net:1433;database=sunshine_ute;user=sqladmin@sunshineutedb;password=Thuyhang2001;encrypt=true;trustServerCertificate=false;hostNameInCertificate=*.database.windows.net;loginTimeout=30;
    show-sql: 'true'
    hibernate:
      ddl-auto: update
logging:
  level:
    org:
      hibernate:
        SQL: DEBUG

