spring:
  datasource:
    username: sqladmin@sunshinedb
    password: Thuyhang2001
    url: jdbc:sqlserver://sunshinedb.database.windows.net:1433;database=sunshinedb;user=sqladmin@sunshinedb;password={your_password_here};encrypt=true;trustServerCertificate=false;hostNameInCertificate=*.database.windows.net;loginTimeout=30;
    show-sql: 'true'
    hibernate:
      ddl-auto: update
logging:
  level:
    org:
      hibernate:
        SQL: DEBUG

